# Reference values from Chris Klausmeier's Mathematica code, generated by
# claude-checks/r-port/r_port_reference.wl. "chop" runs his code unchanged;
# "nochop" runs it with Chop replaced by Identity.

fixture_path <- function(mode) {
    test_path("fixtures", paste0("ref_", mode, ".json"))
}

# NULL if the fixture is missing, so a test can loop over the modes that
# exist. Tests skip only when no fixture exists.
load_ref <- function(mode) {
    skip_if_not_installed("jsonlite")
    if (!any(file.exists(vapply(modes, fixture_path, "")))) skip("no fixtures")
    path <- fixture_path(mode)
    if (!file.exists(path)) return(NULL)
    jsonlite::fromJSON(path, simplifyVector = FALSE)
}

modes <- c("chop", "nochop")

# Run code with the package's Chop option matching the fixture mode.
with_mode <- function(mode, code) {
    old <- options(sweetsoursong.chop = (mode == "chop"))
    on.exit(options(old))
    force(code)
}

num <- function(x) as.numeric(unlist(x))

# Relative difference, with a floor of `floor` on the scale.
rel_diff <- function(a, b, floor = 1) {
    max(abs(a - b) / pmax(abs(b), floor))
}
