// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_ode_cpp
NumericMatrix run_ode_cpp(const double& dt, const double& max_t, const double& Y_delay, const double& B_delay, const double& Y0, const double& B0, const double& A0, const double& H0, const double& D, double A_0, const double& r_Y, const double& r_B, const double& m_Y, const double& m_B, const double& e_B, const double& q_Y, const double& q_B, const double& c_Y, const double& c_B, const double& h_B, const double& h_Y);
RcppExport SEXP _sweetsoursong_run_ode_cpp(SEXP dtSEXP, SEXP max_tSEXP, SEXP Y_delaySEXP, SEXP B_delaySEXP, SEXP Y0SEXP, SEXP B0SEXP, SEXP A0SEXP, SEXP H0SEXP, SEXP DSEXP, SEXP A_0SEXP, SEXP r_YSEXP, SEXP r_BSEXP, SEXP m_YSEXP, SEXP m_BSEXP, SEXP e_BSEXP, SEXP q_YSEXP, SEXP q_BSEXP, SEXP c_YSEXP, SEXP c_BSEXP, SEXP h_BSEXP, SEXP h_YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< const double& >::type max_t(max_tSEXP);
    Rcpp::traits::input_parameter< const double& >::type Y_delay(Y_delaySEXP);
    Rcpp::traits::input_parameter< const double& >::type B_delay(B_delaySEXP);
    Rcpp::traits::input_parameter< const double& >::type Y0(Y0SEXP);
    Rcpp::traits::input_parameter< const double& >::type B0(B0SEXP);
    Rcpp::traits::input_parameter< const double& >::type A0(A0SEXP);
    Rcpp::traits::input_parameter< const double& >::type H0(H0SEXP);
    Rcpp::traits::input_parameter< const double& >::type D(DSEXP);
    Rcpp::traits::input_parameter< double >::type A_0(A_0SEXP);
    Rcpp::traits::input_parameter< const double& >::type r_Y(r_YSEXP);
    Rcpp::traits::input_parameter< const double& >::type r_B(r_BSEXP);
    Rcpp::traits::input_parameter< const double& >::type m_Y(m_YSEXP);
    Rcpp::traits::input_parameter< const double& >::type m_B(m_BSEXP);
    Rcpp::traits::input_parameter< const double& >::type e_B(e_BSEXP);
    Rcpp::traits::input_parameter< const double& >::type q_Y(q_YSEXP);
    Rcpp::traits::input_parameter< const double& >::type q_B(q_BSEXP);
    Rcpp::traits::input_parameter< const double& >::type c_Y(c_YSEXP);
    Rcpp::traits::input_parameter< const double& >::type c_B(c_BSEXP);
    Rcpp::traits::input_parameter< const double& >::type h_B(h_BSEXP);
    Rcpp::traits::input_parameter< const double& >::type h_Y(h_YSEXP);
    rcpp_result_gen = Rcpp::wrap(run_ode_cpp(dt, max_t, Y_delay, B_delay, Y0, B0, A0, H0, D, A_0, r_Y, r_B, m_Y, m_B, e_B, q_Y, q_B, c_Y, c_B, h_B, h_Y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sweetsoursong_run_ode_cpp", (DL_FUNC) &_sweetsoursong_run_ode_cpp, 21},
    {NULL, NULL, 0}
};

RcppExport void R_init_sweetsoursong(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
