# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
landscape_ode <- function(m, R, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, P_max, S_0, q, X, w, z, Y0, B0, N0, dt = 0.1, max_t = 90.0) {
    .Call(`_sweetsoursong_landscape_ode`, m, R, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, P_max, S_0, q, X, w, z, Y0, B0, N0, dt, max_t)
}

#' @export
landscape_constantF_ode <- function(m, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, S_0, X, Y0, B0, dt = 0.1, max_t = 90.0) {
    .Call(`_sweetsoursong_landscape_constantF_ode`, m, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, S_0, X, Y0, B0, dt, max_t)
}

#' @export
landscape_season_ode <- function(m, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, P_max, S_0, q, X, R_hat, mu, sigma, w, z, Y0, B0, add_F = 1.0, dt = 0.1, max_t = 90.0) {
    .Call(`_sweetsoursong_landscape_season_ode`, m, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, P_max, S_0, q, X, R_hat, mu, sigma, w, z, Y0, B0, add_F, dt, max_t)
}

#' @export
run_ode_cpp <- function(dt = 0.01, max_t = 36.0, Y_delay = 0, B_delay = 0, Y0 = 1.0, B0 = 1.0, A0 = 1.46, H0 = 0.0, D = 0.214, A_0 = -999, r_Y = 0.44, r_B = 0.264, m_Y = 0.01, m_B = 0.01, e_B = 0.84, q_Y = 0.022, q_B = 0.0, c_Y = 0.152, c_B = 1, h_B = 0.124, h_Y = 0.044) {
    .Call(`_sweetsoursong_run_ode_cpp`, dt, max_t, Y_delay, B_delay, Y0, B0, A0, H0, D, A_0, r_Y, r_B, m_Y, m_B, e_B, q_Y, q_B, c_Y, c_B, h_B, h_Y)
}

#' @export
one_plant_ode <- function(m, R, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, P_max, q, s_0, h, f_0, F_tilde, u, dt = 0.1, max_t = 90.0, Y0 = 1.0, B0 = 1.0, N0 = 1.0) {
    .Call(`_sweetsoursong_one_plant_ode`, m, R, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, P_max, q, s_0, h, f_0, F_tilde, u, dt, max_t, Y0, B0, N0)
}

#' @export
one_plant_season_ode <- function(m, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, P_max, q, s_0, h, f_0, F_tilde, u, R_hat, t0, k, lambda, dt = 0.1, max_t = 90.0, Y0 = 1.0, B0 = 1.0, N0 = 1.0) {
    .Call(`_sweetsoursong_one_plant_season_ode`, m, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, P_max, q, s_0, h, f_0, F_tilde, u, R_hat, t0, k, lambda, dt, max_t, Y0, B0, N0)
}

#' @export
stoch_test <- function() {
    .Call(`_sweetsoursong_stoch_test`)
}

landscape_weights <- function(x, S_0, q, X, w, z) {
    .Call(`_sweetsoursong_landscape_weights`, x, S_0, q, X, w, z)
}

