# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
one_flower_ode <- function(dt = 0.01, max_t = 36.0, Y_delay = 0, B_delay = 0, Y0 = 1.0, B0 = 1.0, A0 = 1.46, H0 = 0.0, D = 0.214, A_0 = -999, r_Y = 0.44, r_B = 0.264, m_Y = 0.01, m_B = 0.01, e_B = 0.84, q_Y = 0.022, q_B = 0.0, c_Y = 0.152, c_B = 1, h_B = 0.124, h_Y = 0.044) {
    .Call(`_sweetsoursong_one_flower_ode`, dt, max_t, Y_delay, B_delay, Y0, B0, A0, H0, D, A_0, r_Y, r_B, m_Y, m_B, e_B, q_Y, q_B, c_Y, c_B, h_B, h_Y)
}

plant_metacomm_stoch_cpp <- function(n_reps, m, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, u, X, Y0, B0, n_sigma, season_len, season_surv, q, open_sys, dt, max_t, burnin, save_every, summarize) {
    .Call(`_sweetsoursong_plant_metacomm_stoch_cpp`, n_reps, m, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, u, X, Y0, B0, n_sigma, season_len, season_surv, q, open_sys, dt, max_t, burnin, save_every, summarize)
}

plant_metacomm_cpp <- function(m, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, u, X, Y0, B0, open_sys, dt, max_t) {
    .Call(`_sweetsoursong_plant_metacomm_cpp`, m, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, u, X, Y0, B0, open_sys, dt, max_t)
}

#' Bray–Curtis dissimilarity.
#'
#' @param yeast Vector of yeast abundances.
#' @param bact Vector of bacteria abundances.
#'
#' @name dissimilarity
#'
#' @return A single number indicating the mean dissimilarity across the
#'     two vectors.
#'
#' @export
#'
dissimilarity <- function(yeast, bact) {
    .Call(`_sweetsoursong_dissimilarity`, yeast, bact)
}

#' Bray–Curtis dissimilarity on grouped vectors.
#'
#' @inheritParams dissimilarity
#' @param group_size Size of groups within which dissimilarities should be
#'   calculated. It's assumed that the vectors are
#'   all sorted by this grouping such that every `group_size` elements
#'   in the vectors belong to the same group.
#'   The `yeast` and `bact` vectors' lengths should be divisible by
#'   `group_size`.
#' @param overall_mean Single logical for whether to return the overall mean
#'   dissimilarity after grouping. Defaults to `FALSE`.
#'
#'
#' @return If `overall_mean` is `FALSE`, a numeric vector of length
#'   `length(yeast) %/% group_size` with the mean dissimilarities across
#'   the vectors for each group.
#'   Otherwise, a single number indicating the mean dissimilarity across the
#'   two vectors after grouping.
#'
#' @export
#'
dissimilarity_vector <- function(yeast, bact, group_size, overall_mean = FALSE) {
    .Call(`_sweetsoursong_dissimilarity_vector`, yeast, bact, group_size, overall_mean)
}

#' Shannon diversity index.
#'
#' @param yeast Vector of yeast abundances.
#' @param bact Vector of bacteria abundances.
#'
#' @name diversity
#'
#' @return A single number indicating the mean diversity across the
#'     two vectors.
#'
#' @export
#'
diversity <- function(yeast, bact, zero_threshold = 2.220446e-16) {
    .Call(`_sweetsoursong_diversity`, yeast, bact, zero_threshold)
}

#' Shannon diversity index after summing by groups.
#'
#'
#' @inheritParams diversity
#' @param group_size Size of groups within which abundances should be
#'   summed before diversities are calculated.
#'   It's assumed that the vectors are all sorted by this grouping such
#'   that every `group_size` elements in the vectors belong to the same group.
#'   The `yeast` and `bact` vectors' lengths should be divisible by
#'   `group_size`.
#'
#'
#' @return A single number indicating the mean diversities across the
#'   two vectors after summing species by groups.
#'
#' @export
#'
diversity_vector <- function(yeast, bact, group_size, zero_threshold = 2.220446e-16) {
    .Call(`_sweetsoursong_diversity_vector`, yeast, bact, group_size, zero_threshold)
}

