# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
landscape_ode <- function(m, R, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, P_max, u, q, W, w, z, min_F_for_P, Y0, B0, N0, dt = 0.1, max_t = 90.0) {
    .Call(`_sweetsoursong_landscape_ode`, m, R, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, P_max, u, q, W, w, z, min_F_for_P, Y0, B0, N0, dt, max_t)
}

#' @export
landscape_constantF_ode <- function(m, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, u, X, Y0, B0, dt = 0.1, max_t = 90.0) {
    .Call(`_sweetsoursong_landscape_constantF_ode`, m, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, u, X, Y0, B0, dt, max_t)
}

#' @export
landscape_constantF_stoch_ode <- function(n_reps, m, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, u, X, Y0, B0, n_sigma, season_len = NULL, season_surv = 0.01, season_sigma = 0, dt = 0.1, max_t = 100.0) {
    .Call(`_sweetsoursong_landscape_constantF_stoch_ode`, n_reps, m, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, u, X, Y0, B0, n_sigma, season_len, season_surv, season_sigma, dt, max_t)
}

#' @export
landscape_season_ode <- function(m, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, P_max, u, q, W, R_hat, par1, par2, distr_types, w, z, min_F_for_P, Y0, B0, add_F = 1.0, dt = 0.1, max_t = 90.0) {
    .Call(`_sweetsoursong_landscape_season_ode`, m, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, P_max, u, q, W, R_hat, par1, par2, distr_types, w, z, min_F_for_P, Y0, B0, add_F, dt, max_t)
}

#' @export
run_ode_cpp <- function(dt = 0.01, max_t = 36.0, Y_delay = 0, B_delay = 0, Y0 = 1.0, B0 = 1.0, A0 = 1.46, H0 = 0.0, D = 0.214, A_0 = -999, r_Y = 0.44, r_B = 0.264, m_Y = 0.01, m_B = 0.01, e_B = 0.84, q_Y = 0.022, q_B = 0.0, c_Y = 0.152, c_B = 1, h_B = 0.124, h_Y = 0.044) {
    .Call(`_sweetsoursong_run_ode_cpp`, dt, max_t, Y_delay, B_delay, Y0, B0, A0, H0, D, A_0, r_Y, r_B, m_Y, m_B, e_B, q_Y, q_B, c_Y, c_B, h_B, h_Y)
}

#' @export
one_plant_ode <- function(m, R, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, P_max, q, s_0, h, f_0, F_tilde, u, dt = 0.1, max_t = 90.0, Y0 = 1.0, B0 = 1.0, N0 = 1.0) {
    .Call(`_sweetsoursong_one_plant_ode`, m, R, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, P_max, q, s_0, h, f_0, F_tilde, u, dt, max_t, Y0, B0, N0)
}

#' @export
one_plant_season_ode <- function(m, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, P_max, q, s_0, h, f_0, F_tilde, u, R_hat, t0, k, lambda, dt = 0.1, max_t = 90.0, Y0 = 1.0, B0 = 1.0, N0 = 1.0) {
    .Call(`_sweetsoursong_one_plant_season_ode`, m, d_yp, d_b0, d_bp, g_yp, g_b0, g_bp, L_0, P_max, q, s_0, h, f_0, F_tilde, u, R_hat, t0, k, lambda, dt, max_t, Y0, B0, N0)
}

#' @export
stoch_test <- function() {
    .Call(`_sweetsoursong_stoch_test`)
}

make_dist_mat_rcpp <- function(x, y) {
    .Call(`_sweetsoursong_make_dist_mat_rcpp`, x, y)
}

make_spat_wts_rcpp <- function(dm, m) {
    .Call(`_sweetsoursong_make_spat_wts_rcpp`, dm, m)
}

test_R <- function(time, mu, sigma) {
    .Call(`_sweetsoursong_test_R`, time, mu, sigma)
}

landscape_weights <- function(x, S_0, q, X, w, z) {
    .Call(`_sweetsoursong_landscape_weights`, x, S_0, q, X, w, z)
}

#' Bray–Curtis dissimilarity.
#'
#' @param yeast Vector of yeast abundances.
#' @param bact Vector of bacteria abundances.
#'
#' @name dissimilarity
#'
#' @return A single number indicating the mean dissimilarity across the
#'     two vectors.
#'
#' @export
#'
dissimilarity <- function(yeast, bact) {
    .Call(`_sweetsoursong_dissimilarity`, yeast, bact)
}

#' Bray–Curtis dissimilarity on grouped vectors.
#'
#' @inheritParams dissimilarity
#' @param group_size Size of groups within which dissimilarities should be
#'   calculated. It's assumed that the vectors are
#'   all sorted by this grouping such that every `group_size` elements
#'   in the vectors belong to the same group.
#'   The `yeast` and `bact` vectors' lengths should be divisible by
#'   `group_size`.
#' @param overall_mean Single logical for whether to return the overall mean
#'   dissimilarity after grouping. Defaults to `FALSE`.
#'
#'
#' @return If `overall_mean` is `FALSE`, a numeric vector of length
#'   `length(yeast) %/% group_size` with the mean dissimilarities across
#'   the vectors for each group.
#'   Otherwise, a single number indicating the mean dissimilarity across the
#'   two vectors after grouping.
#'
#' @export
#'
dissimilarity_vector <- function(yeast, bact, group_size, overall_mean = FALSE) {
    .Call(`_sweetsoursong_dissimilarity_vector`, yeast, bact, group_size, overall_mean)
}

#' Shannon diversity index.
#'
#' @param yeast Vector of yeast abundances.
#' @param bact Vector of bacteria abundances.
#'
#' @name diversity
#'
#' @return A single number indicating the mean diversity across the
#'     two vectors.
#'
#' @export
#'
diversity <- function(yeast, bact, zero_threshold = 2.220446e-16) {
    .Call(`_sweetsoursong_diversity`, yeast, bact, zero_threshold)
}

